name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '38 1 19 9 *'
    - cron: '1 13 19 9 *'
    - cron: '19 1 20 9 *'
    - cron: '28 12 20 9 *'
    - cron: '50 1 21 9 *'
    - cron: '13 12 21 9 *'
    - cron: '13 1 22 9 *'
    - cron: '7 13 22 9 *'
    - cron: '36 1 23 9 *'
    - cron: '57 13 23 9 *'
    - cron: '28 1 24 9 *'
    - cron: '32 13 24 9 *'
    - cron: '54 0 25 9 *'
    - cron: '8 13 25 9 *'
    - cron: '20 1 26 9 *'
    - cron: '9 12 26 9 *'
    - cron: '30 0 27 9 *'
    - cron: '27 12 27 9 *'
    - cron: '16 1 28 9 *'
    - cron: '8 13 28 9 *'
    - cron: '15 0 29 9 *'
    - cron: '21 1 29 9 *'
    - cron: '19 2 29 9 *'
    - cron: '18 4 29 9 *'
    - cron: '59 5 29 9 *'
    - cron: '56 6 29 9 *'
    - cron: '6 6 29 9 *'
    - cron: '24 7 29 9 *'
    - cron: '56 9 29 9 *'
    - cron: '19 9 29 9 *'
    - cron: '27 10 29 9 *'
    - cron: '17 11 29 9 *'
    - cron: '12 13 29 9 *'
    - cron: '10 13 29 9 *'
    - cron: '41 14 29 9 *'
    - cron: '36 15 29 9 *'
    - cron: '56 16 29 9 *'
    - cron: '54 17 29 9 *'
    - cron: '51 18 29 9 *'
    - cron: '35 19 29 9 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set Git Identity
        run: |
          git config --global user.name "Varun Soni"
          git config --global user.email "varunsoni1234@users.noreply.github.com"

      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push